//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Анкета.
    /// </summary>
    // *** Start programmer edit section *** (Анкета CustomAttributes)

    // *** End programmer edit section *** (Анкета CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АнкетаE", new string[] {
            "ID as \'ID\'",
            "ЛК as \'ЛК\'",
            "Вакансия as \'Вакансия\'",
            "Вакансия.Название as \'Название\'"}, Hidden=new string[] {
            "Вакансия.Название"})]
    [MasterViewDefineAttribute("АнкетаE", "Вакансия", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("АнкетаL", new string[] {
            "ID as \'ID\'",
            "ЛК as \'ЛК\'",
            "Вакансия.Название as \'Название\'"})]
    public class Анкета : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fЛК;
        
        private IIS.HR.Должность fВакансия;
        
        // *** Start programmer edit section *** (Анкета CustomMembers)

        // *** End programmer edit section *** (Анкета CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Анкета.ID CustomAttributes)

        // *** End programmer edit section *** (Анкета.ID CustomAttributes)
        [NotNull()]
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Анкета.ID Get start)

                // *** End programmer edit section *** (Анкета.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Анкета.ID Get end)

                // *** End programmer edit section *** (Анкета.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкета.ID Set start)

                // *** End programmer edit section *** (Анкета.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Анкета.ID Set end)

                // *** End programmer edit section *** (Анкета.ID Set end)
            }
        }
        
        /// <summary>
        /// ЛК.
        /// </summary>
        // *** Start programmer edit section *** (Анкета.ЛК CustomAttributes)

        // *** End programmer edit section *** (Анкета.ЛК CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ЛК
        {
            get
            {
                // *** Start programmer edit section *** (Анкета.ЛК Get start)

                // *** End programmer edit section *** (Анкета.ЛК Get start)
                string result = this.fЛК;
                // *** Start programmer edit section *** (Анкета.ЛК Get end)

                // *** End programmer edit section *** (Анкета.ЛК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкета.ЛК Set start)

                // *** End programmer edit section *** (Анкета.ЛК Set start)
                this.fЛК = value;
                // *** Start programmer edit section *** (Анкета.ЛК Set end)

                // *** End programmer edit section *** (Анкета.ЛК Set end)
            }
        }
        
        /// <summary>
        /// Анкета.
        /// </summary>
        // *** Start programmer edit section *** (Анкета.Вакансия CustomAttributes)

        // *** End programmer edit section *** (Анкета.Вакансия CustomAttributes)
        [PropertyStorage(new string[] {
                "Вакансия"})]
        [NotNull()]
        public virtual IIS.HR.Должность Вакансия
        {
            get
            {
                // *** Start programmer edit section *** (Анкета.Вакансия Get start)

                // *** End programmer edit section *** (Анкета.Вакансия Get start)
                IIS.HR.Должность result = this.fВакансия;
                // *** Start programmer edit section *** (Анкета.Вакансия Get end)

                // *** End programmer edit section *** (Анкета.Вакансия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкета.Вакансия Set start)

                // *** End programmer edit section *** (Анкета.Вакансия Set start)
                this.fВакансия = value;
                // *** Start programmer edit section *** (Анкета.Вакансия Set end)

                // *** End programmer edit section *** (Анкета.Вакансия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АнкетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетаE", typeof(IIS.HR.Анкета));
                }
            }
            
            /// <summary>
            /// "АнкетаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетаL", typeof(IIS.HR.Анкета));
                }
            }
        }
    }
}
