//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчет.
    /// </summary>
    // *** Start programmer edit section *** (Отчет CustomAttributes)

    // *** End programmer edit section *** (Отчет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчетE", new string[] {
            "Дата_проверки as \'Дата_проверки\'"})]
    public class Отчет : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата_проверки;
        
        private IIS.HR.ТЧ_отчета fТЧ_отчета;
        
        // *** Start programmer edit section *** (Отчет CustomMembers)

        // *** End programmer edit section *** (Отчет CustomMembers)

        
        /// <summary>
        /// Дата_проверки.
        /// </summary>
        // *** Start programmer edit section *** (Отчет.Дата_проверки CustomAttributes)

        // *** End programmer edit section *** (Отчет.Дата_проверки CustomAttributes)
        [NotNull()]
        public virtual System.DateTime Дата_проверки
        {
            get
            {
                // *** Start programmer edit section *** (Отчет.Дата_проверки Get start)

                // *** End programmer edit section *** (Отчет.Дата_проверки Get start)
                System.DateTime result = this.fДата_проверки;
                // *** Start programmer edit section *** (Отчет.Дата_проверки Get end)

                // *** End programmer edit section *** (Отчет.Дата_проверки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отчет.Дата_проверки Set start)

                // *** End programmer edit section *** (Отчет.Дата_проверки Set start)
                this.fДата_проверки = value;
                // *** Start programmer edit section *** (Отчет.Дата_проверки Set end)

                // *** End programmer edit section *** (Отчет.Дата_проверки Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.HR.ТЧ_отчета.
        /// </summary>
        // *** Start programmer edit section *** (Отчет.ТЧ_отчета CustomAttributes)

        // *** End programmer edit section *** (Отчет.ТЧ_отчета CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ТЧ_отчета"})]
        public virtual IIS.HR.ТЧ_отчета ТЧ_отчета
        {
            get
            {
                // *** Start programmer edit section *** (Отчет.ТЧ_отчета Get start)

                // *** End programmer edit section *** (Отчет.ТЧ_отчета Get start)
                IIS.HR.ТЧ_отчета result = this.fТЧ_отчета;
                // *** Start programmer edit section *** (Отчет.ТЧ_отчета Get end)

                // *** End programmer edit section *** (Отчет.ТЧ_отчета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отчет.ТЧ_отчета Set start)

                // *** End programmer edit section *** (Отчет.ТЧ_отчета Set start)
                this.fТЧ_отчета = value;
                // *** Start programmer edit section *** (Отчет.ТЧ_отчета Set end)

                // *** End programmer edit section *** (Отчет.ТЧ_отчета Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетE", typeof(IIS.HR.Отчет));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Отчет.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОтчет CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОтчет CustomAttributes)
    public class DetailArrayOfОтчет : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.HR.DetailArrayOfОтчет members)

        // *** End programmer edit section *** (IIS.HR.DetailArrayOfОтчет members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Отчет by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Отчет.
        /// </summary>
        public DetailArrayOfОтчет(IIS.HR.ТЧ_отчета fТЧ_отчета) : 
                base(typeof(Отчет), ((ICSSoft.STORMNET.DataObject)(fТЧ_отчета)))
        {
        }
        
        public IIS.HR.Отчет this[int index]
        {
            get
            {
                return ((IIS.HR.Отчет)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.HR.Отчет dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
