//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудник CustomAttributes)

    // *** End programmer edit section *** (Сотрудник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникE", new string[] {
            "ID as \'ID\'",
            "Дата_приема as \'Дата_приема\'",
            "Отдел as \'Отдел\'",
            "Отдел.Название as \'Название\'",
            "Должность as \'Должность\'",
            "Должность.Название as \'Название\'"}, Hidden=new string[] {
            "Отдел.Название",
            "Должность.Название"})]
    [MasterViewDefineAttribute("СотрудникE", "Отдел", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("СотрудникE", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("СотрудникL", new string[] {
            "ID as \'ID\'",
            "Дата_приема as \'Дата_приема\'",
            "Отдел.Название as \'Название\'",
            "Должность.Название as \'Название\'"})]
    public class Сотрудник : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private System.DateTime fДата_приема;
        
        private IIS.HR.Отдел fОтдел;
        
        private IIS.HR.Должность fДолжность;
        
        // *** Start programmer edit section *** (Сотрудник CustomMembers)

        // *** End programmer edit section *** (Сотрудник CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.ID CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.ID CustomAttributes)
        [NotNull()]
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.ID Get start)

                // *** End programmer edit section *** (Сотрудник.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Сотрудник.ID Get end)

                // *** End programmer edit section *** (Сотрудник.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.ID Set start)

                // *** End programmer edit section *** (Сотрудник.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Сотрудник.ID Set end)

                // *** End programmer edit section *** (Сотрудник.ID Set end)
            }
        }
        
        /// <summary>
        /// Дата_приема.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Дата_приема CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Дата_приема CustomAttributes)
        [NotNull()]
        public virtual System.DateTime Дата_приема
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Дата_приема Get start)

                // *** End programmer edit section *** (Сотрудник.Дата_приема Get start)
                System.DateTime result = this.fДата_приема;
                // *** Start programmer edit section *** (Сотрудник.Дата_приема Get end)

                // *** End programmer edit section *** (Сотрудник.Дата_приема Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Дата_приема Set start)

                // *** End programmer edit section *** (Сотрудник.Дата_приема Set start)
                this.fДата_приема = value;
                // *** Start programmer edit section *** (Сотрудник.Дата_приема Set end)

                // *** End programmer edit section *** (Сотрудник.Дата_приема Set end)
            }
        }
        
        /// <summary>
        /// Сотрудник.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Должность CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.HR.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Должность Get start)

                // *** End programmer edit section *** (Сотрудник.Должность Get start)
                IIS.HR.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (Сотрудник.Должность Get end)

                // *** End programmer edit section *** (Сотрудник.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Должность Set start)

                // *** End programmer edit section *** (Сотрудник.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Сотрудник.Должность Set end)

                // *** End programmer edit section *** (Сотрудник.Должность Set end)
            }
        }
        
        /// <summary>
        /// Сотрудник.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Отдел CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Отдел CustomAttributes)
        [PropertyStorage(new string[] {
                "Отдел"})]
        [NotNull()]
        public virtual IIS.HR.Отдел Отдел
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Отдел Get start)

                // *** End programmer edit section *** (Сотрудник.Отдел Get start)
                IIS.HR.Отдел result = this.fОтдел;
                // *** Start programmer edit section *** (Сотрудник.Отдел Get end)

                // *** End programmer edit section *** (Сотрудник.Отдел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Отдел Set start)

                // *** End programmer edit section *** (Сотрудник.Отдел Set start)
                this.fОтдел = value;
                // *** Start programmer edit section *** (Сотрудник.Отдел Set end)

                // *** End programmer edit section *** (Сотрудник.Отдел Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникE", typeof(IIS.HR.Сотрудник));
                }
            }
            
            /// <summary>
            /// "СотрудникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникL", typeof(IIS.HR.Сотрудник));
                }
            }
        }
    }
}
