//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч_отчета.
    /// </summary>
    // *** Start programmer edit section *** (ТЧ_отчета CustomAttributes)

    // *** End programmer edit section *** (ТЧ_отчета CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч_отчета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧ_отчетаE", new string[] {
            "Результат as \'Результат\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.ID as \'ID\'"}, Hidden=new string[] {
            "Сотрудник.ID"})]
    [AssociatedDetailViewAttribute("ТЧ_отчетаE", "Отчет", "ОтчетE", true, "", "Отчет", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ТЧ_отчетаE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ID")]
    [View("ТЧ_отчетаL", new string[] {
            "Результат as \'Результат\'",
            "Сотрудник.ID as \'ID\'"})]
    public class ТЧ_отчета : ICSSoft.STORMNET.DataObject
    {
        
        private string fРезультат;
        
        private IIS.HR.Сотрудник fСотрудник;
        
        private IIS.HR.DetailArrayOfОтчет fОтчет;
        
        // *** Start programmer edit section *** (ТЧ_отчета CustomMembers)

        // *** End programmer edit section *** (ТЧ_отчета CustomMembers)

        
        /// <summary>
        /// Результат.
        /// </summary>
        // *** Start programmer edit section *** (ТЧ_отчета.Результат CustomAttributes)

        // *** End programmer edit section *** (ТЧ_отчета.Результат CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Результат
        {
            get
            {
                // *** Start programmer edit section *** (ТЧ_отчета.Результат Get start)

                // *** End programmer edit section *** (ТЧ_отчета.Результат Get start)
                string result = this.fРезультат;
                // *** Start programmer edit section *** (ТЧ_отчета.Результат Get end)

                // *** End programmer edit section *** (ТЧ_отчета.Результат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧ_отчета.Результат Set start)

                // *** End programmer edit section *** (ТЧ_отчета.Результат Set start)
                this.fРезультат = value;
                // *** Start programmer edit section *** (ТЧ_отчета.Результат Set end)

                // *** End programmer edit section *** (ТЧ_отчета.Результат Set end)
            }
        }
        
        /// <summary>
        /// Т ч_отчета.
        /// </summary>
        // *** Start programmer edit section *** (ТЧ_отчета.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (ТЧ_отчета.Сотрудник CustomAttributes)
        [PropertyStorage("Сотрудник")]
        [TypeUsage(new string[] {
                "IIS.HR.Сотрудник",
                "IIS.HR.Физ_лицо"})]
        [NotNull()]
        public virtual IIS.HR.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (ТЧ_отчета.Сотрудник Get start)

                // *** End programmer edit section *** (ТЧ_отчета.Сотрудник Get start)
                IIS.HR.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (ТЧ_отчета.Сотрудник Get end)

                // *** End programmer edit section *** (ТЧ_отчета.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧ_отчета.Сотрудник Set start)

                // *** End programmer edit section *** (ТЧ_отчета.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (ТЧ_отчета.Сотрудник Set end)

                // *** End programmer edit section *** (ТЧ_отчета.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Т ч_отчета.
        /// </summary>
        // *** Start programmer edit section *** (ТЧ_отчета.Отчет CustomAttributes)

        // *** End programmer edit section *** (ТЧ_отчета.Отчет CustomAttributes)
        public virtual IIS.HR.DetailArrayOfОтчет Отчет
        {
            get
            {
                // *** Start programmer edit section *** (ТЧ_отчета.Отчет Get start)

                // *** End programmer edit section *** (ТЧ_отчета.Отчет Get start)
                if ((this.fОтчет == null))
                {
                    this.fОтчет = new IIS.HR.DetailArrayOfОтчет(this);
                }
                IIS.HR.DetailArrayOfОтчет result = this.fОтчет;
                // *** Start programmer edit section *** (ТЧ_отчета.Отчет Get end)

                // *** End programmer edit section *** (ТЧ_отчета.Отчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧ_отчета.Отчет Set start)

                // *** End programmer edit section *** (ТЧ_отчета.Отчет Set start)
                this.fОтчет = value;
                // *** Start programmer edit section *** (ТЧ_отчета.Отчет Set end)

                // *** End programmer edit section *** (ТЧ_отчета.Отчет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧ_отчетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧ_отчетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧ_отчетаE", typeof(IIS.HR.ТЧ_отчета));
                }
            }
            
            /// <summary>
            /// "ТЧ_отчетаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧ_отчетаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧ_отчетаL", typeof(IIS.HR.ТЧ_отчета));
                }
            }
        }
    }
}
