//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Физ_лицо.
    /// </summary>
    // *** Start programmer edit section *** (Физ_лицо CustomAttributes)

    // *** End programmer edit section *** (Физ_лицо CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Физ_лицоE", new string[] {
            "ФИО as \'ФИО\'",
            "Контакты as \'Контакты\'",
            "Образование as \'Образование\'",
            "Опыт as \'Опыт\'",
            "ID as \'ID\'",
            "Дата_приема as \'Дата_приема\'",
            "Отдел as \'Отдел\'",
            "Отдел.Название as \'Название\'",
            "Должность as \'Должность\'",
            "Должность.Название as \'Название\'"}, Hidden=new string[] {
            "Отдел.Название",
            "Должность.Название"})]
    [MasterViewDefineAttribute("Физ_лицоE", "Отдел", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("Физ_лицоE", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("Физ_лицоL", new string[] {
            "ФИО as \'ФИО\'",
            "Контакты as \'Контакты\'",
            "Образование as \'Образование\'",
            "Опыт as \'Опыт\'",
            "ID as \'ID\'",
            "Дата_приема as \'Дата_приема\'",
            "Отдел.Название as \'Название\'",
            "Должность.Название as \'Название\'"})]
    public class Физ_лицо : IIS.HR.Сотрудник
    {
        
        private string fФИО;
        
        private string fКонтакты;
        
        private string fОбразование;
        
        private string fОпыт;
        
        // *** Start programmer edit section *** (Физ_лицо CustomMembers)

        // *** End programmer edit section *** (Физ_лицо CustomMembers)

        
        /// <summary>
        /// Контакты.
        /// </summary>
        // *** Start programmer edit section *** (Физ_лицо.Контакты CustomAttributes)

        // *** End programmer edit section *** (Физ_лицо.Контакты CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Контакты
        {
            get
            {
                // *** Start programmer edit section *** (Физ_лицо.Контакты Get start)

                // *** End programmer edit section *** (Физ_лицо.Контакты Get start)
                string result = this.fКонтакты;
                // *** Start programmer edit section *** (Физ_лицо.Контакты Get end)

                // *** End programmer edit section *** (Физ_лицо.Контакты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Физ_лицо.Контакты Set start)

                // *** End programmer edit section *** (Физ_лицо.Контакты Set start)
                this.fКонтакты = value;
                // *** Start programmer edit section *** (Физ_лицо.Контакты Set end)

                // *** End programmer edit section *** (Физ_лицо.Контакты Set end)
            }
        }
        
        /// <summary>
        /// Образование.
        /// </summary>
        // *** Start programmer edit section *** (Физ_лицо.Образование CustomAttributes)

        // *** End programmer edit section *** (Физ_лицо.Образование CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Образование
        {
            get
            {
                // *** Start programmer edit section *** (Физ_лицо.Образование Get start)

                // *** End programmer edit section *** (Физ_лицо.Образование Get start)
                string result = this.fОбразование;
                // *** Start programmer edit section *** (Физ_лицо.Образование Get end)

                // *** End programmer edit section *** (Физ_лицо.Образование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Физ_лицо.Образование Set start)

                // *** End programmer edit section *** (Физ_лицо.Образование Set start)
                this.fОбразование = value;
                // *** Start programmer edit section *** (Физ_лицо.Образование Set end)

                // *** End programmer edit section *** (Физ_лицо.Образование Set end)
            }
        }
        
        /// <summary>
        /// Опыт.
        /// </summary>
        // *** Start programmer edit section *** (Физ_лицо.Опыт CustomAttributes)

        // *** End programmer edit section *** (Физ_лицо.Опыт CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Опыт
        {
            get
            {
                // *** Start programmer edit section *** (Физ_лицо.Опыт Get start)

                // *** End programmer edit section *** (Физ_лицо.Опыт Get start)
                string result = this.fОпыт;
                // *** Start programmer edit section *** (Физ_лицо.Опыт Get end)

                // *** End programmer edit section *** (Физ_лицо.Опыт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Физ_лицо.Опыт Set start)

                // *** End programmer edit section *** (Физ_лицо.Опыт Set start)
                this.fОпыт = value;
                // *** Start programmer edit section *** (Физ_лицо.Опыт Set end)

                // *** End programmer edit section *** (Физ_лицо.Опыт Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Физ_лицо.ФИО CustomAttributes)

        // *** End programmer edit section *** (Физ_лицо.ФИО CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Физ_лицо.ФИО Get start)

                // *** End programmer edit section *** (Физ_лицо.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Физ_лицо.ФИО Get end)

                // *** End programmer edit section *** (Физ_лицо.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Физ_лицо.ФИО Set start)

                // *** End programmer edit section *** (Физ_лицо.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Физ_лицо.ФИО Set end)

                // *** End programmer edit section *** (Физ_лицо.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Физ_лицоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Физ_лицоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Физ_лицоE", typeof(IIS.HR.Физ_лицо));
                }
            }
            
            /// <summary>
            /// "Физ_лицоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Физ_лицоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Физ_лицоL", typeof(IIS.HR.Физ_лицо));
                }
            }
        }
    }
}
